### ISSUE TITLE
doesn't work with IRC conversations

### ISSUE THREAD

**Issue by hasufell** [kgraefe/pidgin-save-conv-order#3]
Tried it with IRC conversations. Doesn't work. Plugin is installed and enabled.

**Comment by kgraefe** [comment]
What did you expect and what happened?
What Pidgin and plugin versions are you using?
What other plugins are you using?
With "conversations" you mean "chats" or "IMs"?

I use it on a daily basis with my IRC accounts, so it does work for me .

**Comment by hasufell** [comment]
It seems to works with jabber conversations, but not with IRC. I usually don't manually open/close IRC windows, since I connect to a bouncer and all windows are opened at start and closed when I quit pidgin. Maybe this plugin requires you to manually open/close before it saves the state?

**Comment by kgraefe** [comment]
Unfortunately you did not answer my questions.

However, I do have a suspicion: Did you add your IRC channels to the buddy list?

**Comment by kgraefe** [comment]
Closed due to no response.

**Comment by hasufell** [comment]
> However, I do have a suspicion: Did you add your IRC channels to the buddy list?

No. IRC channels are joined automatically on start. I don't know what you mean with the distinction `chat` vs `conversation`. Those are all __tabs__ in my window.

**Comment by kgraefe** [comment]
The difference is between "chats" and "IMs". A "chat" is between multpile people (in IRC a "channel") and an "IM"  is between two people (in IRC a "direct message"). "Conversation" is a generic term for both.

However, the plugin stores its information within the buddy list. Therefore you need to add the channels to your buddy list (Menu `Conversation -> Add...`). Otherwise it will not work.
